spring:
  application:
    name: laundry-management

  datasource:
    url: jdbc:mysql://localhost:3306/laundry
    username: root
    password: ayman@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false

jwt:
  secret: "QXltYW5MYXVuZHJ5TWFuYWdlbWVudFN5c3RlbVNlY3JldEtleUZvckpXVFRva2VuMjAyNg=="
  expiration: 86400000
  header: Authorization
  token-prefix: "Bearer "